#user nobody; 
worker_processes 1; 

events { 
	worker_connections 1024; 
} 


http { 
	include mime.types; 
	default_type application/octet-stream; 

	sendfile on; 
	#tcp_nopush on; 
	keepalive_timeout 65; 

	gzip on; 

	server { 
		listen 80; 
		server_name localhost; 

		location / { 
			root html; 
			index index.html index.htm; 
			if ($request_method = 'OPTIONS') { 
				add_header 'Access-Control-Allow-Origin' '*'; 

				add_header 'Access-Control-Allow-Credentials' 'true'; 
				add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS'; 
			
				add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type'; 
		
				add_header 'Access-Control-Max-Age' 1728000; 
				add_header 'Content-Type' 'text/plain charset=UTF-8'; 
				add_header 'Content-Length' 0; 
				return 204; 
			} 
			if ($request_method = 'POST') { 
				add_header 'Access-Control-Allow-Origin' '*'; 
				add_header 'Access-Control-Allow-Credentials' 'true'; 
				add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS'; 
				add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type'; 
			} 
			if ($request_method = 'GET') { 
				add_header 'Access-Control-Allow-Origin' '*'; 
				add_header 'Access-Control-Allow-Credentials' 'true'; 
				add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS'; 
				add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type'; 
			} 
		} 
		location /hls { 
			types {
				application/vnd.apple.mpegurl m3u8;
				video/mp2t ts;
			}
			root /data;
			add_header Cache-Control no-cache;
			add_header Access-Control-Allow-Origin *;
		} 
		location /screens { 
			root /data;
			add_header Cache-Control no-cache;
			add_header Access-Control-Allow-Origin *;
		} 

		location /control { 
			rtmp_control all; 
		} 
		location /stat { 
			rtmp_stat all; 
			rtmp_stat_stylesheet stat.xsl; 
		} 


		error_page 500 502 503 504 /50x.html; 
		location = /50x.html { 
			root html; 
		} 
		location /stream {
			proxy_pass   http://host.docker.internal:4002;
		}

	} 

} 


rtmp { 
	max_streams 1000;
	server { 
		listen 1935; 
		chunk_size 4096; 
		application live { 
			live on; 
			hls on;
			hls_fragment_naming system;
			hls_path /data/hls;
			hls_nested on;
			hls_fragment 5s;
			hls_playlist_length 20s;
			on_publish http://host.docker.internal:4002/stream/auth; 
			on_publish_done http://host.docker.internal:4002/stream/end; 
			recorder preview { 
				record keyframes; 
				record_path /var/rec; 
				record_interval 10s; 
				exec_record_done ffmpeg -i rtmp://localhost:1935/live/$name -vcodec png -vframes 1 -an -f rawvideo -s 480x270 -y /data/screens/$name.png; 
			} 
		} 
	} 
}