export enum ChannelPermissions {
  FULL_ADMIN = 'FULL_ADMIN',
  MODERATE_CHAT = 'MODERATE_CHAT',
  EDIT_STREAM_INFO = 'EDIT_STREAM_INFO',
  BROADCAST = 'BROADCAST',
  EDIT_CHANNEL_INFO = 'EDIT_CHANNEL_INFO',
  PUBLISH_NEWS = 'PUBLISH_NEWS',
}
