export const UploadStatuses = {
  STATUS_NOT_STARTED: 'STATUS_NOT_STARTED',
  STATUS_UPLOADING: 'STATUS_UPLOADING',
  STATUS_PROCESSING: 'STATUS_PROCESSING',
  STATUS_READY: 'STATUS_READY',
  STATUS_ERROR: 'STATUS_ERROR'
}
